### PR TITLE
Improve syntax checker

### PR DESCRIPTION
**Pull request by fonsecas72**
This will add symfony/console to PhpMetrics which allow us to improve code readability and eventually some more improvements in the future.

### CODE REVIEW

**Comment by Halleck45** [comment]
Hi,

I see the advantages, but I not sure that I want to use another library only for this feature : phpmetrics.phar is already very large ( >2.5Mo).

If you're ok, I'll close this PR :/

Thank's you your work !

**Comment by fonsecas72** [comment]
Sure I agree. I have another improvements in mind.
I'll PR again as soon as I finish with them.
BTW, this is not related with this PR but, did you considered using PHP-Parser instead of your own  tokenizer?
(just asking)

**Comment by Halleck45** [comment]
Yes, I would like to use PHPParser + [Hoa Compiler](http://hoa-project.net/En/Literature/Hack/Compiler.html), but that's too complex today :/

Probably for PhpMetrics v2

**Comment by fonsecas72** [comment]
Sounds like a nice hobby :P
Sorry, I don't meant to be nagging but, is there any reason why you don't follow PSR-2 CS?

**Pull request closed without merging**
