### PR TITLE
Fix tests - Maintainability word

### PR DESCRIPTION
**Pull request by fonsecas72**
We should update all namespaces and class names as well.

### CODE REVIEW

**Comment by Halleck45** [comment]
You're faster than me :)

**Comment by Halleck45** [comment]
> We should update all namespaces and class names as well.

Yes, I've merged #94 too fast :/

**Comment by fonsecas72** [comment]
;P

**Comment by Halleck45** [comment]
:)

I've created issue #95

**Comment by fonsecas72** [comment]
> Yes, I've merged #68 too fast :/
I think is better to do this is another issue anyway.

**Pull request merged**
