### PR TITLE
Fixes one fatal error

### PR DESCRIPTION
**Pull request by baptistedeleplace**
see https://github.com/Halleck45/PhpMetrics/issues/73

### CODE REVIEW

**Comment by baptistedeleplace** [comment]
Doesn't really solve the problem but at least it doesn't crash.
In the cases it crashed, it will now render a partial report ; 
In the cases it was stable, nothing changed.

**Comment by Halleck45** [comment]
First version of PhpMetrics has two mode:
+ without OOP analysis (faster)
+ with OOP analysis

I'll remove the first mode as soon as possible. This will fix this issue (so I think that this PR will not be used).

**Comment by baptistedeleplace** [comment]
I tried both mode, and it crashed.
These two little fixes aren't solving the reasons of crashing, but at least
is doesn't crash anymore.

**Comment by Halleck45** [comment]
Ok, you're write, at least this patch avoid Fatal errors. I'll merge it

**Pull request merged**
