### PR TITLE
WIP - Look for a yml config by default

### PR DESCRIPTION
**Pull request by fonsecas72**
We are still missing:

documentation
testing?
the tests are failing?

### CODE REVIEW

**Comment by Halleck45** [comment]
Yes

+ documentation
+ geen tests (tests crashed due to Graphviz. I think that #100 has fixed this problem)
+ unit tests

**Comment by Halleck45** [comment]
Can you rebase please ?

**Comment by fonsecas72** [comment]
Done, we are still lacking tests :(

**Comment by Halleck45** [comment]
Ok. Thanks. I'll not merge today, I'll wait for tests (and I'll try to write them :p )

**Comment by Halleck45** [comment]
I'm late, but... thanks !

**Pull request merged**
