### PR TITLE
travis: PHP 5.6 and 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by fonsecas72** [comment]
please see https://github.com/Halleck45/PhpMetrics/pull/100

**Comment by TomasVotruba** [comment]
@fonsecas72 That PR seems rather complicated without explanations.

**Comment by fonsecas72** [comment]
That seems fair. I'm just saying that you shouldn't open 3 PRs related to one that's already open. Just ask your questions there :-)

**Comment by TomasVotruba** [comment]
These are independent PRs.

**Comment by fonsecas72** [comment]
Why can't we discuss it on one place? Is all about travis yml isn't it?

**Comment by TomasVotruba** [comment]
I prefer to keep independent stuff separated.
What do you want to discuss about?

**Comment by fonsecas72** [comment]
SOLID? Then you should refactor you #120. CS fixes should no go there...

**Comment by TomasVotruba** [comment]
I'd wait for the author first, if this is relevant to his package, before putting any further work.
Can do if accepted.

**Comment by Halleck45** [comment]
This PR duplicates #100 .

Thanks for your help !

**Pull request closed without merging**
