### PR TITLE
Updating Symfony Progress Helper to Progress Bar

### LINKED ISSUE #63: PHP Deprecated Notice re: Symfony ProgressBar
PHP Deprecated:  "Symfony\Component\Console\Helper\ProgressHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\ProgressBar" instead. in /var/www/project/vendor/opine/container/vendor/symfony/console/Symfony/Component/Console/Helper/ProgressHelper.php on line 123

### PR DESCRIPTION
**Pull request by shaunl**
This fixes fixes #63.

### CODE REVIEW

**Comment by UFOMelkor** [comment]
`Symfony\Component\Console\Helper\ProgressBar` is available since 2.5, PhpMetrics requires `symfony\console: ~2.4`

**Comment by Halleck45** [comment]
Hi,

Indeed, you should update the `composer.json` file as following:

    symfony\console: ~2.5

**Comment by shaunl** [comment]
Will do and push again

**Comment by TomasVotruba** [comment]
:+1:

**Comment by Halleck45** [comment]
Thanks for the contribution :) !

**Pull request merged**
