### PR TITLE
Fixes #50 remove parent and self from relational graph

### LINKED ISSUE #50: parent treated as a class
"parent" is shown as a class in the relations graph : (tested on [Mondrian](https://github.com/Trismegiste/Mondrian) )

image

It's not a big deal but it's a little confusing. And I think perhaps it might affect some other metrics if PhpMetrics is seeing this call as a static call ?

Hope this helps :beer:

### PR DESCRIPTION
**Pull request by fonsecas72**

### CODE REVIEW

**Comment by Halleck45** [comment]
Hi,

What do you think about returning the name of the parent instead of "null" ?

**Comment by fonsecas72** [comment]
Is that going to be useful?
The parent class is already caught in another place so their relation is already available.

**Comment by Halleck45** [comment]
I don't know yet

I've to read documentations, but I think that calling a mother class is a call like another. So returning it allows to:
+ count number of effective calls for each method (metric: "average calls by method")
+ build the graph of calls of the application
+ probably more...

**Comment by fonsecas72** [comment]
Yes, you are very likely to be right.
Then we should add more tests .e.g to very the number of calls in a method.

**Comment by Halleck45** [comment]
Hi @fonsecas72. Did you work on this feature ?

**Comment by fonsecas72** [comment]
I might. I don't know how exactly do you want me to fix this. I've just implemented a quick fix.
You think it is good enough? Any suggestion?

**Comment by Halleck45** [comment]
Hi,

for the moment, the quick fix is enough for me. Thanks !

**Pull request merged**
